refactoring

diff --git a/bin/benchmark b/bin/benchmark
--- a/bin/benchmark
+++ b/bin/benchmark
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#  Copyright 2012-2016 Stanislav Senotrusov <stan@senotrusov.com>
+#  Copyright 2012-2019 Stanislav Senotrusov <stan@senotrusov.com>
 #
 #  Licensed under the Apache License, Version 2.0 (the "License");
 #  you may not use this file except in compliance with the License.
@@ -14,44 +14,54 @@
 #  See the License for the specific language governing permissions and
 #  limitations under the License.
 
-set -o nounset && if ! command -v sysbench >/dev/null; then sudo apt install -y sysbench || { echo "Unable to install sysbench" >&2; exit 1; } ; fi && \
-(cd ~ && \
-\
-echo "### CPU ###" && \
-sysbench cpu run && \
-\
-echo "### THREADS ###" && \
-sysbench threads run && \
-\
-echo "### RAM ###" && \
-sysbench memory run --memory-block-size=4096 && \
-\
-sysbench fileio prepare --file-extra-flags=direct && \
-\
-echo "### SEQUENTIAL READ ###" && \
-sysbench fileio run --file-test-mode=seqrd --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=off && \
-\
-echo "### RANDOM READ ###" && \
-sysbench fileio run --file-test-mode=rndrd --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=off && \
-\
-echo "### RANDOM READ QD32 ###" && \
-sysbench fileio run --file-test-mode=rndrd --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=off --file-io-mode=async --file-async-backlog=32 && \
-\
-echo "### SEQUENTIAL WRITE FSYNC EVERY 100 REQ ###" && \
-sysbench fileio run --file-test-mode=seqwr --file-block-size=4096 --file-extra-flags=direct && \
-\
-echo "### RANDOM WRITE FSYNC EVERY 100 REQ ###" && \
-sysbench fileio run --file-test-mode=rndwr --file-block-size=4096 --file-extra-flags=direct && \
-\
-echo "### SEQUENTIAL WRITE NOSYNC ###" && \
-sysbench fileio run --file-test-mode=seqwr --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=on && \
-\
-echo "### RANDOM WRITE NOSYNC ###" && \
-sysbench fileio run --file-test-mode=rndwr --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=on && \
-\
-echo "### RANDOM WRITE NOSYNC QD32 ###" && \
-sysbench fileio run --file-test-mode=rndwr --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=on --file-io-mode=async --file-async-backlog=32 && \
-\
-sysbench fileio cleanup \
-\
-) | tee "${HOME}/$(hostname) $(date +"%Y-%m-%d %H-%M-%S") - benchmark.txt"
+set -o nounset
+
+. deploy-lib.sh || { echo "Unable to load deploy-lib.sh" >&2; exit 1; }
+
+if ! command -v sysbench >/dev/null; then
+  sudo apt install -y sysbench || fail "Unable to install sysbench"
+fi
+
+run-benchmark() (
+  cd "${HOME}" || fail
+
+  echo "### CPU SPEED ###"
+  sysbench cpu run || fail
+  
+  echo "### THREADS ###"
+  sysbench threads run || fail
+  
+  echo "### RAM WRITE, 4KiB BLOCKS ###"
+  sysbench memory run --memory-block-size=4096 || fail
+  
+  sysbench fileio prepare --file-extra-flags=direct || fail
+  
+  echo "### SEQUENTIAL READ ###"
+  sysbench fileio run --file-test-mode=seqrd --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=off || fail
+  
+  echo "### RANDOM READ QD1 ###"
+  sysbench fileio run --file-test-mode=rndrd --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=off || fail
+  
+  echo "### RANDOM READ QD32 ###"
+  sysbench fileio run --file-test-mode=rndrd --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=off --file-io-mode=async --file-async-backlog=32 || fail
+
+  echo "### RANDOM WRITE FSYNC EVERY 100 REQ QD1 ###"
+  sysbench fileio run --file-test-mode=rndwr --file-block-size=4096 --file-extra-flags=direct || fail
+  
+  echo "### RANDOM WRITE NOSYNC QD1 ###"
+  sysbench fileio run --file-test-mode=rndwr --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=on || fail
+  
+  echo "### RANDOM WRITE NOSYNC QD32 ###"
+  sysbench fileio run --file-test-mode=rndwr --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=on --file-io-mode=async --file-async-backlog=32 || fail
+
+  # this should be final tests as they truncate files  
+  echo "### SEQUENTIAL WRITE FSYNC EVERY 100 REQ ###"
+  sysbench fileio run --file-test-mode=seqwr --file-block-size=4096 --file-extra-flags=direct || fail
+
+  echo "### SEQUENTIAL WRITE NOSYNC ###"
+  sysbench fileio run --file-test-mode=seqwr --file-block-size=4096 --file-extra-flags=direct --file-fsync-freq=0 --file-fsync-end=on || fail
+
+  sysbench fileio cleanup || fail
+)
+
+run-benchmark | tee "${HOME}/$(hostname) $(date +"%Y-%m-%d %H-%M-%S") - benchmark.txt"
diff --git a/bin/deploy-data-pi b/bin/deploy-data-pi
--- a/bin/deploy-data-pi
+++ b/bin/deploy-data-pi
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#  Copyright 2012-2016 Stanislav Senotrusov <stan@senotrusov.com>
+#  Copyright 2012-2019 Stanislav Senotrusov <stan@senotrusov.com>
 #
 #  Licensed under the Apache License, Version 2.0 (the "License");
 #  you may not use this file except in compliance with the License.
@@ -19,76 +19,14 @@ set -o nounset
 
 . deploy-lib.sh || { echo "Unable to load deploy-lib.sh" >&2; exit 1; }
 . config.sh || fail "Unable to load config.sh"
-. data-pi/data-pi-lib.sh || fail
-. ubuntu/ubuntu-lib.sh || fail
-. ubuntu/ubuntu-packages.sh || fail
-# . netdata/netdata-lib.sh || fail
 
-ubuntu::deploy-data-pi::as-root() {
-  # System configuration
-  ubuntu::set-inotify-max-user-watches || fail
-  ubuntu::set-hostname "${DATA_PI_HOSTNAME}" || fail
-  ubuntu::set-timezone UTC || fail
-  ubuntu::set-locale en_US.UTF-8 || fail
+. data-pi/data-pi-lib.sh || fail "Unable to load data-pi/data-pi-lib.sh"
+. netdata/netdata-lib.sh || fail "Unable to load netdata/netdata-lib.sh"
+. ubuntu/ubuntu-lib.sh || fail "Unable to load ubuntu/ubuntu-lib.sh"
+. ubuntu/ubuntu-packages.sh || fail "Unable to load ubuntu/ubuntu-packages.sh"
 
-  # Update the system
-  apt::update || fail
-  apt::dist-upgrade || fail
-
-  # Add repositories
-  data-pi::apt::add-ubuntu-raspi2-ppa || fail
-
-  # Install packages
-  apt::install-basic-tools || fail
-  apt::install-tor || fail
-  
-  # error: snap "bw" is not available on stable for this architecture (armhf) but exists on other architectures (amd64).
-  # snap::install-bitwarden-cli || fail
-  
-  data-pi::apt::install-packages || fail
-
-  # Netdata
-  # netdata::install || fail
-  # netdata::configure || fail
-
-  # apt::install-syncthing || fail
-  # systemctl enable --now "syncthing@${SUDO_USER}.service" || fail
-
-  # Cleanup
-  apt::autoremove || fail
-
-  # Install visual stuff
-  data-pi::install-motd || fail
-  data-pi::install-led-heartbeat || fail
-}
-
-
-ubuntu::deploy-data-pi::as-user() {
-  # Shell aliases
-  deploy-lib::install-shellrcd || fail
-  deploy-lib::install-shellrcd::my-computer-deploy-shell-alias || fail
-}
-
-ubuntu::deploy-data-pi::backup() {
-  ubuntu::install-senotrusov-backup-script || fail
-
-  backup-script install data-pi/backup-configs/backup-data-pi || fail
-  backup-data-pi init || fail
-
-  backup-script install data-pi/backup-configs/backup-polina-files || fail
-  backup-polina-files init || fail
-}
-
-ubuntu::deploy-data-pi() {
-  data-pi::ensure-this-is-raspberry-pi || fail
-
-  sudo bash -c "set -o xtrace; set -o nounset; $(declare -f); . config.sh || fail; ubuntu::deploy-data-pi::as-root" || fail "Unable to execute ubuntu::deploy-data-pi::as-root ($?)"
-
-  ubuntu::deploy-data-pi::as-user || fail
-
-  ubuntu::deploy-data-pi::backup || fail
-
-  echo "ubuntu::deploy-data-pi completed"
-}
+if [ -n "${1:-}" ]; then
+  declare -f "$1" >/dev/null || fail "Argument must be a function name: $1"
+fi
 
 "${1:-ubuntu::deploy-data-pi}" "${@:2}" || fail
