${?} -> $?

diff --git a/data-pi/85-raspberry b/data-pi/85-raspberry
--- a/data-pi/85-raspberry
+++ b/data-pi/85-raspberry
@@ -17,15 +17,15 @@
 # https://www.funtoo.org/Raspberry_Pi_Userland_(VCGENCMD)
 
 echo -n "  "
-vcgencmd get_throttled || { echo "Unable to vcgencmd get_throttled (${?})" >&2; }
+vcgencmd get_throttled || { echo "Unable to vcgencmd get_throttled ($?)" >&2; }
 
 echo -n "  "
-vcgencmd measure_temp || { echo "Unable to vcgencmd measure_temp (${?})" >&2; }
+vcgencmd measure_temp || { echo "Unable to vcgencmd measure_temp ($?)" >&2; }
 
 for i in core sdram_c sdram_i sdram_p; do
-  echo "  ${i}_$(vcgencmd measure_volts "${i}" || { echo "Unable to vcgencmd measure_volts ${i} (${?})" >&2; })"
+  echo "  ${i}_$(vcgencmd measure_volts "${i}" || { echo "Unable to vcgencmd measure_volts ${i} ($?)" >&2; })"
 done
 
 echo ""
 
-sudo smartctl -H -A -l error /dev/sda || { echo "Unable to smartctl /dev/sda (${?})" >&2; }
+sudo smartctl -H -A -l error /dev/sda || { echo "Unable to smartctl /dev/sda ($?)" >&2; }
